### ISSUE TITLE
Item 27, p. 82: get method indenting

### ISSUE THREAD

**Issue by agezerlis** [bslatkin/effectivepython#10]
The definition of get in ApiClass seems to be indented by one space less than \__init__ in Child. This shouldn't matter, of course, but it appears to reflect inconsistent indenting in ApiClass itself (probably due to the page break). Everywhere else, the "d" in "def" is in the column below the second "s" in "class".

**Comment by bslatkin** [comment]
Wow amazing catch. You're totally right. Looks like this was correct in my final manuscript but got messed up in the final proof of the book. Thanks for the report!

**Comment by bslatkin** [comment]
This will be fixed in the next printing.
