### ISSUE TITLE
bytes.encode/str.decode -> str.encode/bytes.decode?

### ISSUE THREAD

**Issue by hoxell** [bslatkin/effectivepython#106]
2nd edition, Item 3: Know the Difference between `bytes` and `str`, in the last paragraph on page 9, it reads:

> This fails because the file was opened in read text mode (`'r'`) instead of read binary  mode (`'rb'`). When a handle is in text mode, it uses the system's default text encoding to interpret binary data using `bytes.encode` (for writing) and `str.decode` (for reading) methods.

I think it's supposed be:
> [...] `str.encode` (for writing) and `bytes.decode` (for reading) methods.

**Comment by bslatkin** [comment]
Thank you for the report! Yes, this was wrong. Deduping this with #93
