### ISSUE TITLE
Item 3: (page 10, first line) Use of bytes and str types should be the other way round

### ISSUE THREAD

**Issue by koucos** [bslatkin/effectivepython#109]
The first line on page 10 in 2nd ed.
instead of ...
"using the bytes.encode (for writing) and str.decode (for reading)"
I think it should be the other way round ... i.e.
"using the str.encode (for writing) and bytes.decode (for reading)"
Thank you.

**Comment by bslatkin** [comment]
Thank you for the report! Yes this was mixed up. Deduping with #93
