### ISSUE TITLE
p. 117 paths of execution & workload

### ISSUE THREAD

**Issue by agezerlis** [bslatkin/effectivepython#11]
"When two distinct paths of execution in a program make forward progress in parallel, the time it takes to do the total work is cut in half; the speed of execution is faster by a factor of two."

This implies that there is no overhead whatsoever. More importantly, however, it implicitly assumes that the two distinct paths of execution are given the same workload. This certainly does not have to be the case: if one path of execution is given, say, 10% of the total workload, then the overall time is not cut in half.

**Comment by bslatkin** [comment]
I agree there are a ton of nuances here. My goal here was to provide the simplest explanation possible of the theoretically difference between parallelism and concurrency. I agree there are many practical considerations to consider. I left them out of this spot on purpose. So I'm going to leave this as-is. Thanks.
