### ISSUE TITLE
Item 78: page 373, wrong cross-reference: says “see Item 76”, should be “see Item 77”

### ISSUE THREAD

**Issue by kirisakow** [bslatkin/effectivepython#110]
(2nd ed)
See paragraph which starts with the words “`patch` works for many modules, ...”:

There is a wrong cross-reference:

> in the `setUp` and `tearDown` methods of `TestCase` classes (see Item 76: “Verify Related Behaviors in `TestCase` Subclasses”).

which should be:

> in the `setUp` and `tearDown` methods of `TestCase` classes (see Item 77: “Isolate Tests from Each Other with `setUp`, `tearDown`, `setUpModule`, and `tearDownModule`”).

**Comment by bslatkin** [comment]
Thank you for the report! I agree, that's the better reference.
