### ISSUE TITLE
Item 36, page 140: logical error in the definition of `dropwhile`

### ISSUE THREAD

**Issue by kirisakow** [bslatkin/effectivepython#113]
(2nd ed)

## What the book says

> `dropwhile`, which is the opposite of `takewhile`, skips items from an iterator until the predicate function returns `True` for the first time:

## What the book should say

> `dropwhile`, which is the opposite of `takewhile`, skips items from an iterator as long as the predicate function returns `True`:

**Comment by bslatkin** [comment]
Thank you for the report! It should have read "until the predicate function returns *False* for the first time".
