### ISSUE TITLE
Item 3, page 9, 2nd edition: "%s" invokes `__str__` if there's `__str__` else `__repr__`

### ISSUE THREAD

**Issue by KirkSuD** [bslatkin/effectivepython#117]
Item 3, page 9, 2nd edition: `print('red %s' % b'blue')` "This code actually invokes the `__repr__` method".

I think "%s" invokes `__str__` if there's `__str__` else `__repr__`.

I tried to find online answer, docs, cpython code, and I tested on Python 3.8:

- [stackoverflow](https://stackoverflow.com/a/6005180/)
- [Python 2 docs](https://docs.python.org/2/library/stdtypes.html#string-formatting)
- [Python 3 docs](https://docs.python.org/3/library/string.html#formatstrings)
- [CPython: Objects/unicodeobject.c: unicode_format_arg_format()](https://github.com/python/cpython/blob/ac10947ba79a15bfdaa3ca92c6864214648ab364/Objects/unicodeobject.c#L14205)
- [CPython: Objects/object.c: PyObject_Str()](https://github.com/python/cpython/blob/ac10947ba79a15bfdaa3ca92c6864214648ab364/Objects/object.c#L689)

```
class Test:
    pass

class TestS:
    def __str__(self):
        return "S"

class TestR:
    def __repr__(self):
        return "R"

class TestSR:
    def __str__(self):
        return "S"
    def __repr__(self):
        return "R"

for t in [Test, TestS, TestR, TestSR]:
    print(t.__name__, "%s" % t(), "%r" % t(), f"{t()!s}", f"{t()!r}")

# Test <__main__.Test object at 0x...> (and 3 more...)
# TestS S <__main__.TestS object at 0x...> S <__main__.TestS object at 0x...>
# TestR R R R R
# TestSR S R S R
```

**Comment by bslatkin** [comment]
Thank you for the report! I agree this could be more clear. Also Item 75 about `__repr__` could better explain how delegation to `__str__` and `__repr__` works.
