### ISSUE TITLE
Item 41, p. 148 greatest common denominator

### ISSUE THREAD

**Issue by agezerlis** [bslatkin/effectivepython#13]
On p. 146 we were told the gcd function finds the greatest common divisor. On p. 148, however, this has turned into the greatest common *denominator*. (This is probably the result of thinking of a "lowest common denominator").

**Comment by bslatkin** [comment]
I agree. On page 148 it says "greatest common denominator" and that should be "greatest common divisor".

**Comment by bslatkin** [comment]
This will be fixed in the next printing.
