### ISSUE TITLE
Item 41, p. 149 grammar

### ISSUE THREAD

**Issue by agezerlis** [bslatkin/effectivepython#14]
"However, the cost of doing so is high and may introduce bugs."

To me this reads like "the cost of doing so may introduce bugs", whereas you want to say that  "doing so may introduce bugs", no? Perhaps this is fixed by something like: "However, doing so has a high cost and may introduce bugs."

**Comment by bslatkin** [comment]
You're correct. It should read "However, doing so has a high cost and may introduce bugs."

**Comment by bslatkin** [comment]
This will be fixed in the next printing.
