### ISSUE TITLE
Item 44, p. 162 pickle vs unpickle

### ISSUE THREAD

**Issue by agezerlis** [bslatkin/effectivepython#15]
"You can specify a stable identifier for the function to use for unpickling an object.

...

copyreg.pickle(BetterGameState, pickle_game_state)

...

you can see that the import path to pickle_game_state is encoded

...

b'\x80\x03c__main__\nunpickle_game_state

...

you can't change the path of the module in which the unpickle_game_state function is present"

It's not obvious to me that there's something wrong here, but the repeated jumps from pickling to unpickling can be confusing. For example, the main text speaks of the encoding of pickle_game_state but the output of print(serialized[:35]) contains unpickle_game_state.

I think this is a result of the fact that the first thing that pickle_game_state returns is unpickle_game_state, but even so I was confused reading this portion of the text.

**Comment by bslatkin** [comment]
I believe "you can see that the import path to pickle_game_state" should say "unpickle_game_state" instead.

**Comment by bslatkin** [comment]
This will be fixed in the next printing.
