### ISSUE TITLE
p. 218 index entry

### ISSUE THREAD

**Issue by agezerlis** [bslatkin/effectivepython#17]
"\__class__ variable
super built_in function with, 73"

This should, obviously, say built-in. 

Since we're on the subject, perhaps there should be a distinct index entry on built-in functions (and possibly another one on special methods). Such index entries would be useful when using the book as a reference.

BTW, is the index listing page numbers of only first instances/definitions? I'm asking because e.g. an \__iter__ method is used on p. 135 but not mentioned under \__iter__ in the index.

(I've finished reading the book, so I probably won't be posting any more issues. I thought I'd take the opportunity to say that I really enjoyed Effective Python. Keep up the good work!)

**Comment by bslatkin** [comment]
Yep, it should say "built-in". Adding another reference for `__iter__` sounds like a good idea.

Thank you for all of your feedback, it's very helpful! I hope to get all of these issues fixed in time for the next printing.

And I'm happy to hear you liked the book! Thanks for reading.

**Comment by bslatkin** [comment]
This will be fixed in the next printing.
