### ISSUE TITLE
Item 30, page 92

### ISSUE THREAD

**Issue by fisco** [bslatkin/effectivepython#24]
Bucket class needs:
```
from datetime import datetime
from datetime import timedelta
```

**Comment by bslatkin** [comment]
Thanks for the report! Yes, you're right that this is necessary to make the code work. If you look at the example code in this repo (see https://github.com/bslatkin/effectivepython/blob/master/example_code/item_30.py) you'll see the imports there as you suggested. I omitted these imports to make the example code shorter. So I'm going to mark this issue as working as intended.
