### ISSUE TITLE
Item 24, p. 69, L13: classes vs subclasses

### ISSUE THREAD

**Issue by HayaoSuzuki** [bslatkin/effectivepython#25]
Hi bslatkin.

>Now you can write other `GenericInputData` and `GenericWorker` classes as you wish ...

I think that "other ... subclasses" insted of "other ... classes".

Best.
Hayao (a.k.a. XaroCydeykn on Twitter)

**Comment by bslatkin** [comment]
Yes it should read "subclasses". Good catch! Thanks for the report.

**Comment by bslatkin** [comment]
This will be fixed in the next printing.
