### ISSUE TITLE
Item 35, P.113, L-9, Typographic error?

### ISSUE THREAD

**Issue by HayaoSuzuki** [bslatkin/effectivepython#30]
Hi bslatkin.

In Item 35, P.113, L-9, 
> Then, the return valueof that assinged to `Customer.field_name`.

I think that `Customer.field_name` should have been `Customer.first_name`.

Best.
Hayao Suzuki

**Comment by bslatkin** [comment]
Yes you are correct! Thanks for the report. The bad text is:

> The problem is that the order of operations in the Customer class definition is the opposite of how it reads from left to right. First, the Field constructor is called as Field('first_name'). Then, the return value of that is assigned to Customer.field_name. There’s no way for the Field to know upfront which class attribute it will be assigned to.

**Comment by bslatkin** [comment]
This will be fixed in the next printing.
