### ISSUE TITLE
Item 5, page 13. Small typo(?)

### ISSUE THREAD

**Issue by i-kudryavtsev** [bslatkin/effectivepython#34]
Hi!

You have write:

If you assign a slice with no start or end indexes, you’ll replace its
entire contents with a copy of what’s referenced (instead of allocating
a new list).

```python
b = a
print('Before', a)
a[:] = [101, 102, 103]
assert a is b # Still the same list object
print('After ', a) # Now has different contents
```
I think that it's not interesting to print a after since we want to see that b has not changed. Especially, you have described assignment with slicing in previous example.

Sorry, if I'm wrong.

Best wishes and thanks for the book!

**Comment by bslatkin** [comment]
`b` has changed, though, because `a` and `b` are the same object (`a is b`).

**Comment by i-kudryavtsev** [comment]
Yes, sorry, of course, b has changed, but we have change a explicitly, so, I think, it will be more interesting to print b :-)

**Comment by bslatkin** [comment]
I'm going to leave this as-is. I think "a is b" makes it clear that they're still the same object, so this is subjective.
