### ISSUE TITLE
Item 32 -  __getattribute__(self, name) with super

### ISSUE THREAD

**Issue by netsamir** [bslatkin/effectivepython#37]
Hi Brett,

Thank you for your book.  I have tried to run the following code based on your code.

    class LazyDB(object):
        def __init__(self):
            self.exists = 5
    
        def __getattr__(self, name):
            value = 'Value of __getattr__ %s' % name
            return value
    
        def __getattribute__(self, name):
            print '__getattribute__: %s' % name
            return super().__getattribute__(name)
    
    
    if __name__ == '__main__':
        data = LazyDB()
        print data.exists
    
And I get the following error:

    (!1007) $ python getatt.py
    __getattribute__: exists
    Traceback (most recent call last):
      File "getatt.py", line 16, in <module>
        print data.exists
      File "getatt.py", line 11, in __getattribute__
        return super().__getattribute__(name)
    TypeError: super() takes at least 1 argument (0 given)
    

By the way, I would like to know your opinion about functional programming with python ?

Thank you

**Comment by bslatkin** [comment]
Hi there. This is in the syntax of Python 3 so the super() call has no parameters. For Python 2 you can do super(ClassName, self). This is explained in item 25 in the book.
