### ISSUE TITLE
item 6: slight improvement of "Things to Remember"

### ISSUE THREAD

**Issue by bolry** [bslatkin/effectivepython#39]
Item 6, page 15, bullet 3 reads "... ,consider doing two assignments (one to
slice, another to stride) ...", but since page 14 states
"The first operation should try to reduce the size of the resulting slice by
as much as possible." maybe part of bullet 3 should be phrased, "... ,consider doing two assignments (one to stride, another to slice) ...".

Kind regards,
Bo Rydberg

**Comment by bslatkin** [comment]
Will be fixed in a future release. Thanks
