### ISSUE TITLE
Item 26, p. 74: `_traverse` method of `ToDictMixin` class has unused parameter `key`

### ISSUE THREAD

**Issue by reywood** [bslatkin/effectivepython#42]
As far as I can tell, the `key` parameter isn't used for anything in the method body except to be passed back in for the recursive call.

**Comment by bslatkin** [comment]
If go to page 75 you'll see:

```
def _traverse(self, key, value):
    if (isinstance(value, BinaryTreeWithParent) and
            key == 'parent'):
        return value.value  # Prevent cycles
    else:
    return super()._traverse(key, value)
```

Which shows how the `key` parameter is used to cause the `to_dict` mix-in to exit early for certain attribute names. The parameter is there for extensibility of the child classes.
