### ISSUE TITLE
Item 36, the result of code is not correct on Windows 

### ISSUE THREAD

**Issue by Yggdroot** [bslatkin/effectivepython#46]
```python
def run_sleep(period):
    proc = subprocess.Popen(['sleep', str(period)])
    return proc

start = time.time()
procs = []
for _ in range(10):
    proc = run_sleep(0.1)
    procs.append(proc)

for proc in procs:
    proc.communicate()
end = time.time()
print('Finished in %.3f seconds' % (end - start))
```
the result is "Finished in 1.068 seconds" when run on windows, though it's OK on linux.
I think using this code to illustrate the `"Decoupling the child process from the parent means that the parent process is free to run many child processes in parallel."` may bring confusion for readers.

**Comment by bslatkin** [comment]
Thanks for the report.

How is the `sleep` command running in this case? What shell environment on Windows are you using?

If you increase the period passed to `run_sleep` from `0.1` to something longer like `5`, do you see the same outcome? I'm trying to figure out if this is an effect of the higher process start-up cost on Windows, or synchronous behavior.

**Comment by Yggdroot** [comment]
I think you are right. The result is `Finished in 6.024 seconds` if the code is `run_sleep(5)`.

**Comment by bslatkin** [comment]
Okay good to know! I should increase the time so it's correct in all cases.

**Comment by bslatkin** [comment]
Okay I've made this into 1 second sleep so it's correct on platforms that have slow process start times. I'll get this out in a future release.
