### ISSUE TITLE
item 33 - output shows result of pprint, but print listed - minor

### ISSUE THREAD

**Issue by dec1** [bslatkin/effectivepython#48]
As a very minor point (page 106 of printed book)

```
class Meta(type):
    def __new__(meta, name, bases, class_dict):
        print((meta, name, bases, class_dict))            # change print -> pprint?
        return super().__new__(meta, name, bases, class_dict)
```

is the code snippet, and the output listed is:

```
(<class '__main__.Meta'>,
 'MyClass',
 (<class 'object'>,),
 {'__module__': '__main__',
  '__qualname__': 'MyClass',
  'foo': <function MyClass.foo at 0x1014e2d08>,
  'stuff': 123})
```

This is the output which would result from pprint (not print).
Perhaps the code snippet should be updated to reflect this.

**Comment by bslatkin** [comment]
Yes you're right that is how this works. I did this to make it more readable and to not distract from the goal of this lesson. It's a bit of artistic license for the sake of clarity. I'm going to leave this as is.
