### ISSUE TITLE
Item #13, pg 26, raise KeyError from e

### ISSUE THREAD

**Issue by fja05680** [bslatkin/effectivepython#51]
It is unclear to me what the following line does:
raise KeyError from e

Shouldn't this be simply "raise"  or "ValueError from e" instead of "KeyError" since we are just propagating the error up?

Anyway, an explanation what this does would be beneficial.

thanks!

**Comment by bslatkin** [comment]
The code in question is:

```python
def load_json_key(data, key):
    try:
        result_dict = json.loads(data) # May raise ValueError
    except ValueError as e:
        raise KeyError from e
    else:
        return result_dict[key] # May raise KeyError
```

The idea here is that the `load_json_key` function should only raise `KeyError` exceptions in all cases that they key isn't present. When the JSON data is bad, we still want to raise a `KeyError` instead of callers having to worry about two types of exceptions.

**Comment by fja05680** [comment]
Thanks for that explanation.  Enjoying the book!
