### ISSUE TITLE
Item 31   some codes results are not consistent with the book in python 3.6

### ISSUE THREAD

**Issue by wtbsw** [bslatkin/effectivepython#52]
class Grade(object):
    def __init__(self):
        self._value = 0
    
    def __get__(self, instance, instance_type):
        return self._value
    
    def __set__(self, instance, value):
        if not (0 <= value <= 100):
            raise ValueError('Grade must be between 0 and 100')
        self._value = value
        
first_exam = Exam()
first_exam.writing_grade = 82
first_exam.science_grade = 99
print('Writing', first_exam.writing_grade)
print('Science', first_exam.science_grade)
#results 
#Writing 82
#Science 99

second_exam = Exam()
second_exam.writing_grade = 75
print('Second', second_exam.writing_grade, 'is right')
print('First', first_exam.writing_grade, 'is wrong')
#result 
#Second 75 is right
#First 82 is wrong 

The result is right when the code run , compared with book' result  where
#Second 75 is right
#First 75 is wrong

Glad to discuss with you.
Thank you.

**Comment by bslatkin** [comment]
What version of Python are you using? [The corresponding example code checked into this repository](https://github.com/bslatkin/effectivepython/blob/f8fe5ec958f8235763e40056427d7a56a350a6d8/example_code/item_31.py) works as expected in Python 2 and 3 for me. Maybe you can attach a gist that reproduces this? Please reopen if you can. Thanks.
