### ISSUE TITLE
Simpler/Cleaner Way to solve problem in Item 31

### ISSUE THREAD

**Issue by rrs234** [bslatkin/effectivepython#53]
Implementing a dictionary for the Grade object (page 99) is far from the most efficient method to solve the problem. A much simpler solution is to simply make math_grade, writing_grade, and science_grade members of each Exam object rather than members of the Exam class, shared among all objects of the class. Do this simply by defining them in __init__ rather than at the class level.

See example code here
[item31.txt](https://github.com/bslatkin/effectivepython/files/2590661/item31.txt)

**Comment by horvatha** [comment]
If I use __init__ in the Exam class, it does not check the condition, just replaces the Grade with the value you give, not with the __set__ method I guess.

In the case below (no __init__ in the Exam class) the last row fails because the value is bigger than 100.

    from weakref import WeakKeyDictionary
    
    class Grade:
        def __init__(self):
            self._values = WeakKeyDictionary()
        def __get__(self, instance, instance_type):
            if instance is None: return self
            return self._values.get(instance, 0)
        def __set__(self, instance, value):
            assert isinstance(value, int)
            assert 0 <= value <= 100
            self._values[instance] = value
    
    class Exam:
        math_grade = Grade()
        writing_grade = Grade()
    
    first_exam = Exam()
    second_exam = Exam()
    first_exam.math_grade=88
    first_exam.writing_grade=77
    second_exam.math_grade=99
    second_exam.writing_grade=101

**Comment by Xunius** [comment]
I think @horvatha was right that putting them inside `__init__` makes them not get called at all. Just put some print statements in __get__ and __set__.

Also as @rrs234 's classes are not defined inheriting from `object`, if you run it in python2, the results from 2 Tests() are identical, because not inheriting from `object` makes the descriptor behavior gone, so even the "ExamWrong" gives correct results.

**Comment by bslatkin** [comment]
Agreed with @horvatha. Thank you for responding with a clear explanation. Closing this!
