### ISSUE TITLE
Item 40: Cardinal/intercardinal directions in count_neighbors don't match Grid implementation

### ISSUE THREAD

**Issue by vklikar** [bslatkin/effectivepython#54]
The directions in `count_neighbors` are defined this way:
```
            N(y + 1, x)
W(y, x - 1)             E(y, x + 1)
            S(y - 1, x)
```

However, when this is applied to `Grid`, which queries and assigns via `[y][x]`, it results in the directions being mirrored:
```
 S
W E
 N
```

**Comment by bslatkin** [comment]
Thanks for the report. I'll plan to fix this.

**Comment by bslatkin** [comment]
This will be fixed in a future release. Thank you
