### ISSUE TITLE
Some confusion in Item 32 regarding the order of hasattr and __getattr__

### ISSUE THREAD

**Issue by Xunius** [bslatkin/effectivepython#55]
Hi,
I think there is some ambiguity in the section describing the order of `hasattr` and `__getattr__` in Item 32.
The texts read:

```
These functions also look in the instance dictionary for an attribute name before calling __getattr__.
```

Then the code results shown below:

```
>>>
Before:  {'exists': 5}
Called __getattr__(foo)
foo exists: True
After: {'exists': 5, 'foo': 'Value for foo'}
foo exists: True
```

The result part seem to suggest that `__getattr__` is called **before** looking into the instance dictionary, rather than **after** that. So in the description above, it should the be reverse: "These functions also look in the instance dictionary for an attribute name **after** calling `__getattr__`."

Or, by "looking in the instance dictionary" python calls `__getattr__` under the hood?

In either case, I think there is some confusion.

**Comment by bslatkin** [comment]
`getattr` and `hasattr` will try to retrieve the given attribute name in the object's `__dict__`. If the key is present, then `__getattr__` will not be called on the object at all. Here's a slight update to the output that may make it more clear.

```python
data = LoggingLazyDB()  # Implements __getattr__
print('Before:         ', data.__dict__)
print('Has first foo:  ', hasattr(data, 'foo'))
print('After:          ', data.__dict__)
print('Has second foo: ', hasattr(data, 'foo'))
```

```
>>>
Before:          {'exists': 5}
* Called __getattr__('foo'), populating instance dictionary
Has first foo:   True
After:           {'exists': 5, 'foo': 'Value for foo'}
Has second foo:  True
```

So I believe the text is valid as-is.
