### ISSUE TITLE
Item 57 ambiguity in "There is no difference between running a python program under a debugger"?

### ISSUE THREAD

**Issue by Xunius** [bslatkin/effectivepython#56]
Hi,

In Item 57, there is a line:
```
There is no difference between running a python program under a debugger and running it normally.
```
I guess what you are trying to say is you run a python script in debug mode in the same way you run it normally (like `python main.py`). 

But when I first read it what came to my mind is the python script is executed the same way in debug mode v.s. in normal mode. Which I believe is not the case.

So could there be an ambiguity?

Besides, from my experiences it seems that in debug mode python's speed is dropped, even for those parts that contain no trace points. I'm not 100% sure about this though, but I do remember in few cases where my computations run slower if I use `python -m pdb`. Maybe someone could help clarify.

**Comment by bslatkin** [comment]
I think it's subjective, because I'm not talking about running it under `pdb` but how to initiate `pdb` (i.e., no special build is required). But I'll clarity this with:

> This means that there is no difference between starting a Python program in order to run the debugger and starting it normally.
