### ISSUE TITLE
Item 24: Handle not closed in example code

### ISSUE THREAD

**Issue by boris-n** [bslatkin/effectivepython#57]
The `read` method of the example code of `PathInputData` is show as
```python
def read(self):
    return open(self.path).read()
```
This will not close the opened handle. Better is to use a `with`-construct here:
```python
def read(self):
    with open(self.path) as f:
        return f.read()
```

Greetings!

**Comment by bslatkin** [comment]
Yep that would be better. I'll fix this in a future revision. Thanks
