### ISSUE TITLE
Item 46: wrong count of accesses for bisect_left

### ISSUE THREAD

**Issue by boris-n** [bslatkin/effectivepython#58]
In item 46, you wrote that searching a list of 1 million items takes roughly the same amount of time as using index to linearly search a list of 14 items.

I assume that it is not the absolute time you are discussing here but the number of accesses to list items. In this case, searching with bisect_left in a list of 1 million items requires (roughly) 20 accesses, because log2(10**6) is (approximately) 19.93. So searching an item in a list of 1 million items takes roughly the same amount of time as using index to linearly search a list of 20 items, not 14 items. (Still a lot faster ...)

Following a small program as proof:
```python
from bisect import bisect_left

class MyList(list):
    def __getitem__(self, index):
        print("Fetching element at %u" % index)
        return super().__getitem__(index)

x = MyList(range(10**6))
bisect_left(x, 991234)
```

This program outputs all list accesses from bisect_left (20 accesses here):
```
Fetching element at 500000
Fetching element at 750000
Fetching element at 875000
Fetching element at 937500
Fetching element at 968750
Fetching element at 984375
Fetching element at 992188
Fetching element at 988282
Fetching element at 990235
Fetching element at 991212
Fetching element at 991700
Fetching element at 991456
Fetching element at 991334
Fetching element at 991273
Fetching element at 991243
Fetching element at 991228
Fetching element at 991236
Fetching element at 991232
Fetching element at 991234
Fetching element at 991233
```

**Comment by bslatkin** [comment]
Great point. I used natural log instead of log2. I'll make sure to fix this in a future release.
