### ISSUE TITLE
Item 21 - class definition

### ISSUE THREAD

**Issue by jonfernandes** [bslatkin/effectivepython#63]
The return statement is not within the method definition.
i.e. it should be this 
```
class Sorter:
...
def __call__(self, x):
        if x in self.group:
            self.found = True
            return (0, x)
        return (1, x)
```

NOT
```
class Sorter:
...
def __call__(self, x):
        if x in self.group:
            self.found = True
            return (0, x)
return (1, x)
```

**Comment by bslatkin** [comment]
@jonfernandes Thanks for the report. I don't see it this way in my copy of the book. Can you provide more context about where you saw it this way? Was it an ebook version or kindle or something like that? Thanks

**Comment by cihati** [comment]
@bslatkin I came here to report the same bug as well. Seems like @jonfernandes forgot to follow up on your question. Here's where I see it:

![image](https://user-images.githubusercontent.com/461998/81494745-cb8c6b00-92b3-11ea-9119-d2c0f3639a89.png)

from https://learning.oreilly.com/library/view/effective-python-90/9780134854717/ch03.xhtml

**Comment by bslatkin** [comment]
Gotcha. This appears to be an issue with the O'Reilly eBook specifically. I'll have to follow up with the publisher to figure this out. Thanks for the extra info @cihati!

**Comment by bslatkin** [comment]
Going to follow up on this one for post-production
