### ISSUE TITLE
syntax highlighting in item 13, p. 26

### ISSUE THREAD

**Issue by agezerlis** [bslatkin/effectivepython#7]
Three lines from the bottom of p. 26: raise should be in purple.

**Comment by bslatkin** [comment]
Great catch! This was correct (blue because it's a keyword) in my original manuscript. It's also correct in other parts of the book. But it must have gotten set to normal text sometime during the proofing process. Thank you for the report.

**Comment by bslatkin** [comment]
This will be fixed in the next printing.
