### ISSUE TITLE
Downloading code for v2 of the book 

### ISSUE THREAD

**Issue by pamdemonia** [bslatkin/effectivepython#71]
The archives of code samples for the book are for the first edition only and git won't allow me to clone the repo. Just got the book, very excited to get into it during this month of sheltering in place. Thanks!

**Comment by bslatkin** [comment]
Sorry for my delay in replying here. Could you provide some links that show this problem? The new example code is here:

https://github.com/bslatkin/effectivepython/tree/master/example_code
