### ISSUE TITLE
Item #37: Inner for loop should be indented

### ISSUE THREAD

**Issue by panos73** [bslatkin/effectivepython#72]
First of all, thanks for a really great book.
In the online version of the book, https://learning.oreilly.com/library/view/effective-python-90/9780134854717/ch05.xhtml#ch5
it is correctly mentioned "—the average_grade method now has a loop within a loop and is difficult to read", but the indentation does not reflect in the code.

**Comment by cihati** [comment]
![image](https://user-images.githubusercontent.com/461998/81500423-d0b0e080-92da-11ea-9d46-b2e6d6e5eefe.png)

**Comment by bslatkin** [comment]
This appears to be the same root cause as issue #63.

**Comment by bslatkin** [comment]
Duplicate of #63
