### ISSUE TITLE
item 34: unnecessary use of iter()

### ISSUE THREAD

**Issue by cihati** [bslatkin/effectivepython#75]
![image](https://user-images.githubusercontent.com/461998/81500080-554e2f80-92d8-11ea-86e6-43a13e692db5.png)

![image](https://user-images.githubusercontent.com/461998/81500139-bb3ab700-92d8-11ea-8305-84d58502f1d2.png)

https://learning.oreilly.com/library/view/effective-python-90/9780134854717/ch04.xhtml

AFAIU, it doesn't matter if you use `iter()` or not here, so it's unnecessary.

**Comment by bslatkin** [comment]
Technically you're correct, yes. Thanks for the report!
