### ISSUE TITLE
Item 24, p. 68: InputData vs GenericInputData

### ISSUE THREAD

**Issue by agezerlis** [bslatkin/effectivepython#8]
"are up to the InputData concrete subclass to interpret":

as shown in the code that follows, this is actually referring to GenericInputData concrete subclasses, not InputData ones. This construction is probably a result of the way the previous paragraph (on p. 67) is set up, where InputData is essentially used as a synonym of GenericInputData.

**Comment by bslatkin** [comment]
Good catch. I think you're right and that sentence should be `GenericInputData` instead of `InputData`. Thanks for the report.

**Comment by bslatkin** [comment]
This will be fixed in the next printing.
