### ISSUE TITLE
item 11, page 44, note at the bottom of the page

### ISSUE THREAD

**Issue by srob1** [bslatkin/effectivepython#85]
The note at the bottom of page 44 (item 11) states:

> "the expression somelist[-n:] will work fine when n is greater than one..."

I believe this should say "greater than zero" rather than "greater than one":

>  "the expression somelist[-n:] will work fine when n is greater than zero..."

since somelist[-1:] works just fine and slices the last item of somelist.

**Comment by bslatkin** [comment]
Thank you for the report. Yes that's right! I will change this.
