### ISSUE TITLE
Item 25: the number 5

### ISSUE THREAD

**Issue by agezerlis** [bslatkin/effectivepython#9]
In this item the number 5 is used in three distinct ways: i) as the initial value, ii) as the number that is added on in PlusFive, and iii) as the number that multiplies the value in TimesFive and TimesFiveCorrect. 

The latter two uses are clear enough, but perhaps using a different number (e.g. 3) for the initial value might help distinguish between the first use and the other two. This applies especially in the case of expressions like 5 * (5 + 2). Drawing the right conclusion is not too difficult given the explanations in the text, but using a different starting value would eliminate this issue altogether. 

(Obviously, this is not an erratum, merely a suggestion for possible improvement).

**Comment by bslatkin** [comment]
That's a good suggestion. In hindsight I should have done it that was so each combination of operator (multiply, add, etc) and number (2, 5, etc) were different for each class demonstrated. That would have been more clear. I'm not sure if I'll be able to incorporate this now but I appreciate the feedback. Thanks!
