### ISSUE TITLE
item 3: should be str.encode and bytes.decode at top of page 10 

### ISSUE THREAD

**Issue by peterbayerle** [bslatkin/effectivepython#90]
am I misreading this? quick check in the interpreter shows bytes.encode doesn't exist:
```
>>> bytes.encode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'bytes' has no attribute 'encode'
>>> str.encode
<method 'encode' of 'str' objects>
```
and it wouldn't make sense to encode bytes prior to writing anyway right?

**Comment by peterbayerle** [comment]
noticed this issue is already open...

**Comment by bslatkin** [comment]
Thank you for the report. Deduping with #93
