### ISSUE TITLE
Item #85: inconsistent spacing after `.`

### ISSUE THREAD

**Issue by jrib** [bslatkin/effectivepython#91]
I'm reading the book via oreilly.com in case the issue isn't present in other formats.

In "Item 85: Use Packages to Organize Modules and Provide Stable APIs":

Two examples seem to have spaces after `.` (in imports and attribute access).  I learned that the python interpreter is actually ok with this (!)... I assume at the very least the space in `utils. __all__` isn't intentional.  The style for relative imports using `. models` instead of `.models` might be intentional but I don't think it's conventional.

In the import:

```python
from . models import Projectile
```

In the imports and later in `utils. __all__`:

```python
# __init__.py
__all__ = []
from . models import *

__all__ += models.__all__
from . utils import *
__all__ += utils. __all__
```

**Comment by bslatkin** [comment]
Thank you for the repot! I agree the space between should be removed.
