### ISSUE TITLE
Item 90: "Python 4" mentioned

### ISSUE THREAD

**Issue by jrib** [bslatkin/effectivepython#92]
Currently, "A better approach is to use from `__future__` import annotations, which is available in Python 3.7 and will become the default in Python 4" is stated in the book.

Currently, [pep-563](https://www.python.org/dev/peps/pep-0563/) says, "In Python 3.10 this will become the default behavior. Use of annotations incompatible with this PEP is no longer supported".  I think it used to say "Python 4" because Guido didn't like double-digit version numbers (?).  Seems like that's changed however.  The book should be updated to say "Python 3.10" instead of "Python 4".

**Comment by bslatkin** [comment]
Yes the PEP changed
