### ISSUE TITLE
Item 3: when a handle is in text mode

### ISSUE THREAD

**Issue by feynmanpan** [bslatkin/effectivepython#93]
hi brett:

In 2ed, you wrote:
"when a handle is in text mode, it uses the system's default text encoding to interpret binary data using the **_bytes.encode_** (for writing) and **_str.decode_** (for reading) methods."

I think that should be:
..... str.encode (for writing) and bytes.decode (for reading) ....

please confirm, thanks!

**Comment by bslatkin** [comment]
Yes that's right. These were swapped. Thank you for the report!
