### ISSUE TITLE
Item36-Page138-help function

### ISSUE THREAD

**Issue by forrestgao** [bslatkin/effectivepython#97]
> Whenever you find yourself dealing with tricky iteration code, it’s
> worth looking at the itertools documentation again to see if there’s
> anything in there for you to use (see help(itertools)). 

 help(itertools)   should be: help('itertools')

**Comment by bslatkin** [comment]
Thank you for the report! My assumption is that the `itertools` module is already imported, so this is calling the help function on that module object.
