### ISSUE TITLE
Item 37: unused variable in for loop

### ISSUE THREAD

**Issue by hong-dev** [bslatkin/effectivepython#98]
Item 37, in `class WeightedGradebook`, there's an unused variable(`subject`) in for loop as below. :slightly_smiling_face:  
Maybe `for subject, scores in by_subject.items()` can be changed to **`for scores in by_subject.values()`**? :hushed:  

![Screenshot from 2021-04-08 01-19-22](https://user-images.githubusercontent.com/53142539/113900203-8bf23a00-9808-11eb-8f63-b0446b9976fa.png)

Reference: [link to related example_code](https://github.com/bslatkin/effectivepython/blob/master/example_code/item_37.py#L130)
Thank you! :bow: :pray:

**Comment by bslatkin** [comment]
Thank you for the report! Yes, you're right -- this would be simpler code and get rid of the unused variable.
